const teamData = {
  'ANA': 'Anaheim Ducks',
  'ARI': 'Arizona Coyotes',
  'BOS': 'Boston Bruins',
  'BUF': 'Buffalo Sabres',
  'CAR': 'Carolina Hurricanes',
  'CBJ': 'Columbus Blue Jackets',
  'CGY': 'Calgary Flames',
  'CHI': 'Chicago Blackhawks',
  'COL': 'Colorado Avalanche',
  'DAL': 'Dallas Stars',
  'DET': 'Detroit Red Wings',
  'EDM': 'Edmonton Oilers',
  'FLA': 'Florida Panthers',
  'LAK': 'Los Angeles Kings',
  'MIN': 'Minnesota Wild',
  'MTL': 'Montreal Canadiens',
  'NJD': 'New Jersey Devils',
  'NSH': 'Nashville Predators',
  'NYI': 'New York Islanders',
  'NYR': 'New York Rangers',
  'OTT': 'Ottawa Senators',
  'PHI': 'Philadelphia Flyers',
  'PIT': 'Pittsburgh Penguins',
  'SJS': 'San Jose Sharks',
  'SEA': 'Seattle Kraken',
  'STL': 'St. Louis Blues',
  'TBL': 'Tampa Bay Lightning',
  'TOR': 'Toronto Maple Leafs',
  'VAN': 'Vancouver Canucks',
  'VGK': 'Vegas Golden Knights',
  'WPG': 'Winnipeg Jets',
  'WSH': 'Washington Capitals',
};

export default teamData;
